<?php
// app/Services/ThemeService.php

namespace App\Services;

use App\Models\ThemeSetting;
use Illuminate\Support\Facades\Cache;

class ThemeService
{
    const CACHE_KEY = 'theme.dynamic.css';

    /**
     * Defaults mirror the :root / .light-mode values already shipped
     * in common.css. Only variables listed here are editable from the
     * admin panel — add more keys here (and re-seed) to expose them.
     */
    public static function defaults(): array
    {
        return [
            'dark' => [
                'primary-color'    => '#0d56de',
                'bg-main'          => '#0a0f1d',
                'black-color'      => '#0f1522',
                'black-color-1'    => '#161d2d',
                'black-color-1white' => '#161d2d',
                'black-color-2'    => '#090f1c',
                'black-color-2p'   => '#090f1c',
                'black-color-3'    => '#272d3a',
                'black-color-4'    => '#313848',
                'black-color-5'    => '#404d60',
                'black-color-6'    => '#acb5bd',
                'white-color'      => '#ffffff',
                'white-color-70'   => '#ffffffb3',
                'green-color'      => '#00a569',
                'payment-color'    => '#50b748',
                'error-color'      => '#f03d3e',
                'saleText-color'   => '#dd4949',
            ],
            'light' => [
                'primary-color'    => '#0d56de',
                'bg-main'          => '#0a0f1d',
                'black-color'      => '#eff3f6',
                'black-color-1'    => '#ffffff',
                'black-color-1white' => '#ffffff',
                'black-color-2'    => '#dfdfdf',
                'black-color-2p'   => '#090f1c',
                'black-color-3'    => '#1d68f51f',
                'black-color-4'    => '#cdd2dd',
                'black-color-5'    => '#bbbec3',
                'black-color-6'    => '#c4c5c5',
                'white-color'      => '#0f1522',
                'white-color-70'   => '#000000b3',
                'green-color'      => '#00a569',
                'payment-color'    => '#50b748',
                'error-color'      => '#f03d3e',
                'saleText-color'   => '#dd4949',
            ],
        ];
    }

    /** Defaults merged with whatever admin has saved in the DB. */
    public static function all(): array
    {
        $defaults = self::defaults();
        $saved = ThemeSetting::all()->groupBy('mode');

        foreach (['dark', 'light'] as $mode) {
            foreach ($saved->get($mode, []) as $row) {
                if (array_key_exists($row->variable, $defaults[$mode])) {
                    $defaults[$mode][$row->variable] = $row->value;
                }
            }
        }

        return $defaults;
    }

    public static function generateCss(): string
    {
        $all = self::all();

        $css = "/* auto-generated by ThemeService — do not edit by hand */\n";
        $css .= ":root {\n";
        foreach ($all['dark'] as $var => $val) {
            $css .= "  --{$var}: {$val};\n";
        }
        $css .= "}\n\n.light-mode {\n";
        foreach ($all['light'] as $var => $val) {
            $css .= "  --{$var}: {$val};\n";
        }
        $css .= "}\n";

        return $css;
    }

    public static function cachedCss(): string
    {
        return Cache::rememberForever(self::CACHE_KEY, fn() => self::generateCss());
    }

    public static function clearCache(): void
    {
        Cache::forget(self::CACHE_KEY);
    }

    /** Cache-busting query string for the <link> tag in the layout. */
    public static function version(): string
    {
        $latest = ThemeSetting::max('updated_at');
        return $latest ? md5((string) $latest) : 'default';
    }
}
