sonar.projectKey=artofliving-promax
sonar.projectName=Art of Living Promax
sonar.sources=.
sonar.host.url=http://localhost:9000

sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**,node_modules/**,public/build/**,public/storage/**