<?php

namespace App\Support;

class WebThemeColorPresets
{
    public static function all(): array
    {
        return [
            // 0. Default — the site's original palette, exactly as shipped in
            //    ThemeService::defaults(). Lets admins pick "Default" from the
            //    same preset picker instead of using a separate Reset action.
            'default' => [
                'name' => 'Default (Site Original)',
                'dark' => [
                    'primary-color'      => '#0d56de',
                    'bg-main'            => '#0a0f1d',
                    'black-color'        => '#0f1522',
                    'black-color-1'      => '#161d2d',
                    'black-color-1white' => '#161d2d',
                    'black-color-2'      => '#090f1c',
                    'black-color-2p'     => '#090f1c',
                    'black-color-3'      => '#272d3a',
                    'black-color-4'      => '#313848',
                    'black-color-5'      => '#404d60',
                    'black-color-6'      => '#acb5bd',
                    'white-color'        => '#ffffff',
                    'white-color-70'     => '#ffffffb3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'light' => [
                    'primary-color'      => '#0d56de',
                    'bg-main'            => '#f5f7fa',
                    'black-color'        => '#eff3f6',
                    'black-color-1'      => '#ffffff',
                    'black-color-1white' => '#ffffff',
                    'black-color-2'      => '#dfdfdf',
                    'black-color-2p'     => '#090f1c',
                    'black-color-3'      => '#1d68f51f',
                    'black-color-4'      => '#1d68f51f',
                    'black-color-5'      => '#bbbec3',
                    'black-color-6'      => '#c4c5c5',
                    'white-color'        => '#0f1522',
                    'white-color-70'     => '#000000b3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'swatch' => ['#0d56de', '#404d60', '#090f1c', '#eff3f6', '#0f1522'],
            ],

            // 1. Romantic Blush — Classic love, romantic warmth & feminine elegance
            'romantic_blush' => [
                'name' => 'Romantic Blush',
                'dark' => [
                    'primary-color'      => '#E11D48',
                    'bg-main'            => '#2c050e',
                    'black-color'        => '#30060f',
                    'black-color-1'      => '#3c0713',
                    'black-color-1white' => '#3c0713',
                    'black-color-2'      => '#26040c',
                    'black-color-2p'     => '#26040c',
                    'black-color-3'      => '#4b0918',
                    'black-color-4'      => '#612734',
                    'black-color-5'      => '#FB7185',
                    'black-color-6'      => '#fca3b0',
                    'white-color'        => '#ffffff',
                    'white-color-70'     => '#ffffffb3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'light' => [
                    'primary-color'      => '#E11D48',
                    'bg-main'            => '#f5f7fa',
                    'black-color'        => '#FFF1F2',
                    'black-color-1'      => '#ffffff',
                    'black-color-1white' => '#FFFFFF',
                    'black-color-2'      => '#650d20',
                    'black-color-2p'     => '#650d20',
                    'black-color-3'      => '#FFF5F6',
                    'black-color-4'      => '#fed1d7',
                    'black-color-5'      => '#FB7185',
                    'black-color-6'      => '#fdb1bc',
                    'white-color'        => '#0f1522',
                    'white-color-70'     => '#000000b3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'swatch' => ['#E11D48', '#FB7185', '#E11D48', '#F43F5E', '#FFF1F2'],
            ],

            // 2. Royal Purple — Majestic, regal luxury & premium matchmaking
            'royal_purple' => [
                'name' => 'Royal Purple',
                'dark' => [
                    'primary-color'      => '#6D28D9',
                    'bg-main'            => '#17092c',
                    'black-color'        => '#190a30',
                    'black-color-1'      => '#200d3d',
                    'black-color-1white' => '#200d3d',
                    'black-color-2'      => '#140826',
                    'black-color-2p'     => '#140826',
                    'black-color-3'      => '#28124d',
                    'black-color-4'      => '#422e62',
                    'black-color-5'      => '#9333EA',
                    'black-color-6'      => '#b97af1',
                    'white-color'        => '#ffffff',
                    'white-color-70'     => '#ffffffb3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'light' => [
                    'primary-color'      => '#6D28D9',
                    'bg-main'            => '#f5f7fa',
                    'black-color'        => '#F5F3FF',
                    'black-color-1'      => '#ffffff',
                    'black-color-1white' => '#FFFFFF',
                    'black-color-2'      => '#311262',
                    'black-color-2p'     => '#311262',
                    'black-color-3'      => '#FAF5FF',
                    'black-color-4'      => '#dcc3fa',
                    'black-color-5'      => '#9333EA',
                    'black-color-6'      => '#c48ff3',
                    'white-color'        => '#0f1522',
                    'white-color-70'     => '#000000b3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'swatch' => ['#6D28D9', '#9333EA', '#7C3AED', '#A855F7', '#F5F3FF'],
            ],

            // 3. Crimson Velvet — Auspicious wedding red, celebratory & passionate
            'crimson_velvet' => [
                'name' => 'Crimson Velvet',
                'dark' => [
                    'primary-color'      => '#BE123C',
                    'bg-main'            => '#1f040c',
                    'black-color'        => '#22040d',
                    'black-color-1'      => '#2a0510',
                    'black-color-1white' => '#2a0510',
                    'black-color-2'      => '#1b040a',
                    'black-color-2p'     => '#1b040a',
                    'black-color-3'      => '#350714',
                    'black-color-4'      => '#4d2530',
                    'black-color-5'      => '#E11D48',
                    'black-color-6'      => '#ec6c88',
                    'white-color'        => '#ffffff',
                    'white-color-70'     => '#ffffffb3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'light' => [
                    'primary-color'      => '#BE123C',
                    'bg-main'            => '#f5f7fa',
                    'black-color'        => '#FFF1F2',
                    'black-color-1'      => '#ffffff',
                    'black-color-1white' => '#FFFFFF',
                    'black-color-2'      => '#55081b',
                    'black-color-2p'     => '#55081b',
                    'black-color-3'      => '#FFE4E6',
                    'black-color-4'      => '#f8bcc8',
                    'black-color-5'      => '#E11D48',
                    'black-color-6'      => '#ee839a',
                    'white-color'        => '#0f1522',
                    'white-color-70'     => '#000000b3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'swatch' => ['#BE123C', '#E11D48', '#9F1239', '#E11D48', '#FFF1F2'],
            ],

            // 4. Emerald Luxe — Prosperity, growth, harmony & auspicious beginnings
            'emerald_luxe' => [
                'name' => 'Emerald Luxe',
                'dark' => [
                    'primary-color'      => '#059669',
                    'bg-main'            => '#011610',
                    'black-color'        => '#011912',
                    'black-color-1'      => '#011f16',
                    'black-color-1white' => '#011f16',
                    'black-color-2'      => '#01130e',
                    'black-color-2p'     => '#01130e',
                    'black-color-3'      => '#02271c',
                    'black-color-4'      => '#204137',
                    'black-color-5'      => '#10B981',
                    'black-color-6'      => '#64d2ad',
                    'white-color'        => '#ffffff',
                    'white-color-70'     => '#ffffffb3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'light' => [
                    'primary-color'      => '#059669',
                    'bg-main'            => '#f5f7fa',
                    'black-color'        => '#F0FDF4',
                    'black-color-1'      => '#ffffff',
                    'black-color-1white' => '#FFFFFF',
                    'black-color-2'      => '#02442f',
                    'black-color-2p'     => '#02442f',
                    'black-color-3'      => '#E8FBF0',
                    'black-color-4'      => '#b8ecd7',
                    'black-color-5'      => '#10B981',
                    'black-color-6'      => '#7cd8ba',
                    'white-color'        => '#0f1522',
                    'white-color-70'     => '#000000b3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'swatch' => ['#059669', '#10B981', '#047857', '#10B981', '#F0FDF4'],
            ],

            // 5. Ocean Teal — Serenity, trust, clarity & modern sophistication
            'ocean_teal' => [
                'name' => 'Ocean Teal',
                'dark' => [
                    'primary-color'      => '#0D9488',
                    'bg-main'            => '#041615',
                    'black-color'        => '#041817',
                    'black-color-1'      => '#051f1d',
                    'black-color-1white' => '#051f1d',
                    'black-color-2'      => '#041312',
                    'black-color-2p'     => '#041312',
                    'black-color-3'      => '#062724',
                    'black-color-4'      => '#24413e',
                    'black-color-5'      => '#14B8A6',
                    'black-color-6'      => '#66d1c5',
                    'white-color'        => '#ffffff',
                    'white-color-70'     => '#ffffffb3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'light' => [
                    'primary-color'      => '#0D9488',
                    'bg-main'            => '#f5f7fa',
                    'black-color'        => '#F0FDFA',
                    'black-color-1'      => '#ffffff',
                    'black-color-1white' => '#FFFFFF',
                    'black-color-2'      => '#06433d',
                    'black-color-2p'     => '#06433d',
                    'black-color-3'      => '#E6FAF8',
                    'black-color-4'      => '#b9ece5',
                    'black-color-5'      => '#14B8A6',
                    'black-color-6'      => '#7ed8ce',
                    'white-color'        => '#0f1522',
                    'white-color-70'     => '#000000b3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'swatch' => ['#0D9488', '#14B8A6', '#0F766E', '#06B6D4', '#F0FDFA'],
            ],

            // 6. Sunset Amber — Auspicious saffron, festive warmth & vibrant energy
            'sunset_amber' => [
                'name' => 'Sunset Amber',
                'dark' => [
                    'primary-color'      => '#EA580C',
                    'bg-main'            => '#2d1003',
                    'black-color'        => '#321203',
                    'black-color-1'      => '#3e1604',
                    'black-color-1white' => '#3e1604',
                    'black-color-2'      => '#270e02',
                    'black-color-2p'     => '#270e02',
                    'black-color-3'      => '#4e1d04',
                    'black-color-4'      => '#633822',
                    'black-color-5'      => '#F97316',
                    'black-color-6'      => '#fba468',
                    'white-color'        => '#ffffff',
                    'white-color-70'     => '#ffffffb3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'light' => [
                    'primary-color'      => '#EA580C',
                    'bg-main'            => '#f5f7fa',
                    'black-color'        => '#FFFBEB',
                    'black-color-1'      => '#ffffff',
                    'black-color-1white' => '#FFFFFF',
                    'black-color-2'      => '#692805',
                    'black-color-2p'     => '#692805',
                    'black-color-3'      => '#FFF7ED',
                    'black-color-4'      => '#fed9b6',
                    'black-color-5'      => '#F97316',
                    'black-color-6'      => '#fcb27f',
                    'white-color'        => '#0f1522',
                    'white-color-70'     => '#000000b3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'swatch' => ['#EA580C', '#F97316', '#EA580C', '#FBBF24', '#FFFBEB'],
            ],

            // 7. Imperial Gold — VIP matrimonial, high-net-worth elite & champagne gold
            'imperial_gold' => [
                'name' => 'Imperial Gold',
                'dark' => [
                    'primary-color'      => '#B45309',
                    'bg-main'            => '#1c0c03',
                    'black-color'        => '#1f0e03',
                    'black-color-1'      => '#261104',
                    'black-color-1white' => '#261104',
                    'black-color-2'      => '#180b03',
                    'black-color-2p'     => '#180b03',
                    'black-color-3'      => '#311505',
                    'black-color-4'      => '#4a3123',
                    'black-color-5'      => '#D97706',
                    'black-color-6'      => '#e6a75d',
                    'white-color'        => '#ffffff',
                    'white-color-70'     => '#ffffffb3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'light' => [
                    'primary-color'      => '#B45309',
                    'bg-main'            => '#f5f7fa',
                    'black-color'        => '#FFFDF7',
                    'black-color-1'      => '#ffffff',
                    'black-color-1white' => '#FFFFFF',
                    'black-color-2'      => '#512504',
                    'black-color-2p'     => '#512504',
                    'black-color-3'      => '#FEF3C7',
                    'black-color-4'      => '#f6dcbb',
                    'black-color-5'      => '#D97706',
                    'black-color-6'      => '#eab476',
                    'white-color'        => '#0f1522',
                    'white-color-70'     => '#000000b3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'swatch' => ['#B45309', '#D97706', '#92400E', '#F59E0B', '#FFFDF7'],
            ],

            // 8. Sapphire Elite — Deep corporate navy & verified profile trustworthiness
            'sapphire_elite' => [
                'name' => 'Sapphire Elite',
                'dark' => [
                    'primary-color'      => '#1D4ED8',
                    'bg-main'            => '#060d1e',
                    'black-color'        => '#070e21',
                    'black-color-1'      => '#081128',
                    'black-color-1white' => '#081128',
                    'black-color-2'      => '#050b1b',
                    'black-color-2p'     => '#050b1b',
                    'black-color-3'      => '#0a1531',
                    'black-color-4'      => '#27314a',
                    'black-color-5'      => '#3B82F6',
                    'black-color-6'      => '#80aef9',
                    'white-color'        => '#ffffff',
                    'white-color-70'     => '#ffffffb3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'light' => [
                    'primary-color'      => '#1D4ED8',
                    'bg-main'            => '#f5f7fa',
                    'black-color'        => '#F8FAFC',
                    'black-color-1'      => '#ffffff',
                    'black-color-1white' => '#FFFFFF',
                    'black-color-2'      => '#0d2361',
                    'black-color-2p'     => '#0d2361',
                    'black-color-3'      => '#F1F5F9',
                    'black-color-4'      => '#c9dcfa',
                    'black-color-5'      => '#3B82F6',
                    'black-color-6'      => '#93bafa',
                    'white-color'        => '#0f1522',
                    'white-color-70'     => '#000000b3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'swatch' => ['#1D4ED8', '#3B82F6', '#1E3A8A', '#2563EB', '#F8FAFC'],
            ],

            // 9. Plum Wine — Rich berry/burgundy, deeply romantic & intimate luxury
            'plum_wine' => [
                'name' => 'Plum Wine',
                'dark' => [
                    'primary-color'      => '#831843',
                    'bg-main'            => '#15061c',
                    'black-color'        => '#17061e',
                    'black-color-1'      => '#1d0824',
                    'black-color-1white' => '#1d0824',
                    'black-color-2'      => '#120519',
                    'black-color-2p'     => '#120519',
                    'black-color-3'      => '#25092b',
                    'black-color-4'      => '#3f2744',
                    'black-color-5'      => '#BE185D',
                    'black-color-6'      => '#d56996',
                    'white-color'        => '#ffffff',
                    'white-color-70'     => '#ffffffb3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'light' => [
                    'primary-color'      => '#831843',
                    'bg-main'            => 'f5f7fa',
                    'black-color'        => '#FDF4FF',
                    'black-color-1'      => '#ffffff',
                    'black-color-1white' => '#FFFFFF',
                    'black-color-2'      => '#3b0b1e',
                    'black-color-2p'     => '#3b0b1e',
                    'black-color-3'      => '#FAF5FF',
                    'black-color-4'      => '#edbdd6',
                    'black-color-5'      => '#BE185D',
                    'black-color-6'      => '#db80a6',
                    'white-color'        => '#0f1522',
                    'white-color-70'     => '#000000b3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'swatch' => ['#831843', '#BE185D', '#701A75', '#A21CAF', '#FDF4FF'],
            ],

            // 10. Midnight Slate — Minimalist modern executive, sleek dark graphite feel
            'midnight_slate' => [
                'name' => 'Midnight Slate',
                'dark' => [
                    'primary-color'      => '#334155',
                    'bg-main'            => '#04060a',
                    'black-color'        => '#05070b',
                    'black-color-1'      => '#06090e',
                    'black-color-1white' => '#06090e',
                    'black-color-2'      => '#030509',
                    'black-color-2p'     => '#030509',
                    'black-color-3'      => '#090c13',
                    'black-color-4'      => '#27292f',
                    'black-color-5'      => '#475569',
                    'black-color-6'      => '#87909e',
                    'white-color'        => '#ffffff',
                    'white-color-70'     => '#ffffffb3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'light' => [
                    'primary-color'      => '#334155',
                    'bg-main'            => '#f5f7fa',
                    'black-color'        => '#F8FAFC',
                    'black-color-1'      => '#ffffff',
                    'black-color-1white' => '#FFFFFF',
                    'black-color-2'      => '#171d26',
                    'black-color-2p'     => '#171d26',
                    'black-color-3'      => '#F1F5F9',
                    'black-color-4'      => '#ccd1d7',
                    'black-color-5'      => '#475569',
                    'black-color-6'      => '#9aa2ac',
                    'white-color'        => '#0f1522',
                    'white-color-70'     => '#000000b3',
                    'green-color'        => '#00a569',
                    'payment-color'      => '#50b748',
                    'error-color'        => '#f03d3e',
                    'saleText-color'     => '#dd4949',
                ],
                'swatch' => ['#334155', '#475569', '#1E293B', '#475569', '#F8FAFC'],
            ],
        ];
    }

    public static function find(string $key): ?array
    {
        return self::all()[$key] ?? null;
    }
}